// POKEDEX
export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILED = "FETCH_POKEMONS_FAILED";
export const LOAD_MORE_POKEMONS = "LOAD_MORE_POKEMONS";
