// POKEDEX
export const FETCH_POKEMONS_START = "FETCH_POKEMONS_START";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILED = "FETCH_POKEMONS_FAILED";
export const LOAD_MORE_POKEMONS = "LOAD_MORE_POKEMONS";
export const LOAD_MORE_POKEMONS_START = "LOAD_MORE_POKEMONS_START";
